### ISSUE TITLE
.bag file

### ISSUE THREAD

**Issue by torchlidar** [nickcharron/lidar_snow_removal#3]
Hello.
First of all, thank you for providing great codes.
I have a few questions.

1. Could you upload the reference bag file of this code?

2. Does catkin_make cause the following error?
![image](https://user-images.githubusercontent.com/65699167/98665234-c1484800-238e-11eb-8359-6c508d772bfd.png)
![image](https://user-images.githubusercontent.com/65699167/98665192-aece0e80-238e-11eb-86a5-9c94405c945e.png)

I'll wait for your answer.
Thank You.

**Comment by nickcharron** [comment]
The datasets used for this paper can be found here: http://cadcd.uwaterloo.ca/

With regards to our compile error, I have not encountered this error, however I have not tested on ROS Melodic (only Kinetic) so there could be version issues. Please let me know if you solve this.

**Comment by torchlidar** [comment]
Thank you for your kind response.

Is the .bag file provided in that dataset?
I'll try to implement it in the ROS Melodic environment and tell you something unusual.


Thank you.
