### ISSUE TITLE
On the meaning of formula in DROR. h

### ISSUE THREAD

**Issue by GuoliangPeng** [nickcharron/lidar_snow_removal#5]
What is the meaning of this part of the formula? It has not been seen in the paper. What are the settings of these values
![屏幕截图](https://user-images.githubusercontent.com/7499423/192224277-99740118-02c3-407d-8f64-71aa3641eea3.png)

**Comment by nickcharron** [comment]
Good catch, looks like this was a bug that was introduced when refactoring to the function to be templated. I have fixed it in commit https://github.com/nickcharron/lidar_snow_removal/commit/0b64f1a04cb569409a946ae4b8149c27c2c44d86
