### ISSUE TITLE
Realtime performance?

### ISSUE THREAD

**Issue by pallavbhalla** [nickcharron/lidar_snow_removal#6]
@nickcharron Thanks for sharing the resources.
I tried using the **DROR** filter. I had a few questions regarding the same:

1. Does it perform realtime? It didn't work in realtime for me.
2. How did you come up with the default parameters in this [**CODE**](https://github.com/nickcharron/lidar_snow_removal/blob/0b64f1a04cb569409a946ae4b8149c27c2c44d86/include/DROR.h#L109)?

Waiting for your response.

**Comment by nickcharron** [comment]
1. Yes it performed in real-time for me, but it depends heavily on the parameters, as well as the number of points for your lidar.
2. I manually tuned them to get the precision & recall that I thought was best for my situation
